## Read in positions of EcoRI cut sites (generated by Perl)
setwd("~/Desktop/Bootcamp") # Change this to the directory containing your ecoRI_sites_chr22.txt file
pos <- read.table("ecoRI_sites_chr22.txt", header=F)
pos <- pos[,1] # convert single column table to vector
pos <- sort(pos) # sort the vector in case it was not sorted already
head(pos)

## Compute some useful quantities related to cut sites
lengthChr22 <- 35194600
avgDistPerCutMeasured <- lengthChr22 / length(pos)
avgDistPerCutNaive <- 4^6                           # Under the naive model, a 6-mer DNA sequences will occur 1 in every 4^6 positions
numberOfCutsMeasured <- length(pos)
numberOfCutsNaive <- lengthChr22 / 4^6

## A neat trick for computing the difference between adjacent elements in a vector
dist <- pos[-1] - pos[-length(pos)] # will return a vector of distances between EcoRI sites

## START PDF GRAPHICS BLOCK
pdf("RestrictionEnzymeFragmentSizeDistributions.pdf", width=10, height=5) # everything between here and dev.off() will get printed to a pdf in the current directory

## Set graphical parameters
par(mfrow=c(1,2))
xlim <- c(0,20000)
breaks <- seq(0,200000,500)
col <- c("blue", "red")
lty <- c(2, 3)
lwd <- 3

## Plot histogram of distances between EcoRI cut sites and superimpose exponential models
## "Blue" distribution reflects the cut distances for naive exponential model (1 cut every 4^6 = 4096 bp)
## "Red" distribution reflects the cut distances for exponential model with the computed average cut rate (computed from Perl output)
hist(dist, xlim=xlim, breaks=breaks, col="gray", freq=FALSE, xlab="Distance between EcoRI cut sites (bp)", ylab="Probability Density", main="Histogram of distance between EcoRI cuts\n(chr22)")
curve(dexp(x, rate=1/avgDistPerCutNaive),    add = TRUE, col=col[1], lty=lty[1], lwd=lwd)
curve(dexp(x, rate=1/avgDistPerCutMeasured), add = TRUE, col=col[2], lty=lty[2], lwd=lwd)
legend("topright", legend=c("Distance, Exponential model, naive rate", "Distance, Exponential model, computed rate"), col=col, lty=lty, lwd=lwd, cex=0.8)

## Plot naive Poisson model of total cut site count in chr22 and compare to measured value of total cuts
x <- 0:10000
y <- dpois(0:10000, lambda=numberOfCutsNaive)
plot(x, y, type="l", lwd=lwd, col=col[1], xlab="Total number of EcoRI cuts in chr22", ylab="Probability Density", main="Poisson model for total number of EcoRI cuts\n(chr22)")
abline(v=numberOfCutsMeasured, lwd=lwd, lty=lty[1], col=col[2]) # add a vertical line
polygon(x,y,col="skyblue") # fills in area under the Poisson density curve
legend("topleft", legend=c("Total cuts, naive Poisson model", "Total cuts, computed"), col=col, lty=lty, lwd=lwd, cex=0.8, bg="white")
dev.off()
## END PDF GRAPHICS BLOCK

## Compute a one-tailed p-value for deviation from naive model -- i.e. probability of observing numberOfCutsMeasured or fewer
## under the null hypothesis that numberOfCutsNaive reflects true Poisson rate (1 cut per 4096 bp or ~8600 total cuts in chr22)
ppois(numberOfCutsMeasured, lambda=numberOfCutsNaive)
